export const labels = {
  login: 'Login Doccure',
  areUdoctor: 'Are you Doctor?',
  loginNow: 'Login Now',
  forgotPassword: 'Forgot Password ?',
  register: 'REGISTER',
  dntHaveAccount: 'Dont have an login ?',
  signUp: 'Signup Now!',
  facebook: 'Facebook',
  google: 'Google',
  doctorRegister: 'Doctor Register',
  notaDoctor: 'Not a Doctor?',
  alreadyAccount: 'Already have an account ?',
  registerLogin: 'Login Now!',
  resetPassword: 'Reset password',
  goBackLogin: 'Go back to login ?',
  changePassword: 'Change Password',
  booked: 'Appointment booked',
  success: 'Successfully!',
  bookedWith: 'Appointment booked with',
  viewInvoice: 'View Invoice',
  searchNow: 'Search Now',
  specialities: 'Specialities ',
  viewAll: 'View All',
  findDoctors: 'Find Doctors',
  bookAppoinitment: 'Book Appointment',
  logOut: 'Logout',
  bookingDate: 'Booking Date',
  confirm: 'Confirm',
  view: 'View',
  print: 'Print',
  prescriptions: 'Prescriptions',
  paidOn: 'Paid on',
  aboutUs: 'About us',
  aboutMe: 'About me',
  education: 'Education',
  experience: 'Work & Experience',
  services: 'Services',
  specializations: 'Specializations',
  text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.',
  replay: 'Replay',
  recommend: 'Recommend?',
  recommendDoctor: 'I recommend the doctor',
  showFeedback: 'Show all feedback',
  today: 'Today',
  openNow: 'Open Now',
  monday: 'Monday',
  tuesday: 'Tuesday',
  wednesday: 'Wednesday',
  thrusday: 'Thrusday',
  friday: 'Friday',
  saturday: 'Saturday',
  sunday: 'Sunday',
  closed: 'Closed',
  lastBooking: 'Last Booking',
  totalPatient: 'Total Patients',
  todayPatient: 'Today Patients',
  todayAppointments: 'Today Appointments',
  upcomingAppointments: 'Upcoming Appointments',
  order: 'Order:',
  issued: 'Issued:',
  from: 'Invoice From',
  to: 'Invoice To',
  payment: 'Payment Method',
  appPages: 'App Pages',
  authentication: 'Authentication',
  date: 'Date',
  gender: 'Gender',
  specialist: 'Select Specialist',
  applyFilter: 'Apply Filter',
  basicInformation: 'Basic Information',
  username: 'Username',
  email: 'E-mail',
  firstName: 'First Name',
  lastName: 'Last Name',
  phoneNo: 'Phone Number',
  fromBasic: 'From',
  next: 'Next',
  biography: 'Biography',
  clinicInfo: 'Clinic Info',
  clinicName: 'Clinic Name',
  clinicAddress: 'Clinic Address',
  clinicImage: 'Clinic Image',
  contactDetails: 'Contact Details',
  done: 'Done',

  name: 'Name',
  mobileNumber: 'Mobile Number',
  createPassword: 'Create Password',
  emailOrUserName: 'Email or Username',

  password: 'Password',
  searchByDr: 'Search by Doctor',
  timings: 'Timings',
  fromTime: 'From',
  toTime: 'To',
  paymentInformation:"Payment Information",
  creditCard:'Credit Card',
  tcMessage:"Terms & Conditions",
  readAndAccept:"I have read and accept",
  paypal:"Paypal",
  gobacktoLogin: "Go back to Login ?",
  confirmpassword: "Confirm password",
};
